goravel/goravel

Dockerfile
README.md
README_zh.md
config/cors.go
go.mod

1. Add CORS config file;
2. Add Dockerfile;

Upgrade v1.3.0

---

README.md
README_zh.md
app/providers/app_service_provider.go
app/providers/auth_service_provider.go
app/providers/console_service_provider.go
app/providers/event_service_provider.go
app/providers/queue_service_provider.go
config/app.go
go.mod

Upgrade v1.6.0

---

app/providers/validation_service_provider.go
config/app.go
go.mod

1. Add facades.Validation module;

Upgrade 1.7.0

---

.github/workflows/issue-auto-reply.yml
.github/workflows/issue-close-question.yml
.github/workflows/welcome.yml

There are not many problems now, so I think we can simplify the template first. If needed, we can add it back in the future.

Optimize workflows

---

.github/workflows/issue-auto-reply.yml

fix: CI auto reply

---

README.md
README_zh.md
go.mod

Upgrade v1.12.1

---

go.mod

Fix facades.Gate() returns nil

Upgrade v1.12.2

---

README.md
README_zh.md
go.mod

Upgrade v1.12.3

---

app/providers/database_service_provider.go
config/app.go
database/seeders/database_seeder.go

feat: Database Seeding Functionality

---

.github/workflows/pr-check-title.yml
README.md
README_zh.md

feat: optimize README and workflow

feat: optimize README and workflow

---

README.md
README_zh.md
go.mod

Upgrade v1.12.5

---

README.md
README_zh.md
go.mod

Upgrade v1.12.6

---

go.mod

Upgrade v1.12.7

---

README.md
README_zh.md
config/app.go
go.mod
tests/feature/example_test.go
tests/test_case.go

Closes https://github.com/goravel/goravel/issues/73
Add some template files.

feat: Add testing feature

---

go.mod

chore: update go 1.20

---

config/filesystems.go

Closes https://github.com/goravel/goravel/issues/264
We don't need to add a soft connection, just add a routing is ok: `facades.Route().Static("storage", "./storage/app/public")`

fix: [#264] [Bug] Add a soft connection description to the filesystem module

---

config/hashing.go

Closes # 
Follow Laravel’s adjustments
github.com/laravel/laravel#6245

feat: Increase bcrypt rounds to 12

---

config/http.go

feat: add body limit config

---

config/app.go

feat: New Localization module

---

config/http.go

Revert "feat: add body limit config"

---

config/http.go

feat: Add body_limit config for gin

---

go.mod

Upgrade v1.13.7

---

config/http.go

feat: add header_limit config

---

config/filesystems.go
config/http.go

fix: config

---

README.md
README_zh.md
go.mod

upgrade: gin v1.1.7

---

config/session.go

Related To: https://github.com/goravel/goravel/issues/357
Other PR: https://github.com/goravel/goravel/pull/370

feat: add session module 2

---

go.mod

Upgrade v1.13.8

---

go.mod

upgrade: v1.13.9

---

go.mod

upgrade: v1.13.10

---

README.md
README_zh.md
go.mod

upgrade: v1.14.0

---

go.mod

upgrade: v1.14.1

---

.gitignore
README.md
README_zh.md
go.mod

Bowen/merge v1.14.1

---

config/app.go

Closes https://github.com/goravel/goravel/issues/?

feat: add lang path config

---

go.mod

upgrade: v1.14.3

---

app/providers/validation_service_provider.go

feat: add filter

---

config/session.go

RelatedTo https://github.com/goravel/goravel/issues/457

feat: [#457] Remove session lottery config

---

main.go

feat: remove Shutdown

---

go.mod

upgrade: v1.14.8

---

go.mod

Closes https://github.com/goravel/goravel/issues/528

fix: [#528] GraphQL request causing errors from request body parsing

---

go.mod

upgrade: v1.14.9

---

config/database.go

Closes https://github.com/goravel/goravel/issues/539

chore: [#539] Remove the SQL migrator module

---

config/database.go

Put `schema` configuration item into `.env` file and set default value
Closes https://github.com/goravel/goravel/issues/?

config.Env("DB_SCHEMA", "public")

---

config/queue.go

Closes https://github.com/goravel/goravel/issues/?

feat: add queue config

---

artisan

- add `artisan` shell file to simplify `go run  . artisan`, such as `./arrisan key:generate`

feat: add `artisan` shell file

---

artisan

add `artisan` shell file to simplify `go run . artisan`, such as `./arrisan key:generate`

feat:add artisan shell file

---

go.mod

upgrade: v1.15.4

---

go.mod

This pull request includes a small change to the `go.mod` file. The change updates the version of the `github.com/goravel/framework` dependency from v1.15.4 to v1.15.5.

upgrade: v1.15.5

---

go.mod

upgrade: v1.15.6

---

.gitignore

Closes https://github.com/goravel/goravel/issues/

More secure env

---

go.mod

This pull request includes updates to the dependencies in the `go.mod` file. The most important changes involve updating the versions of two dependencies.
Dependency updates:
* Updated `github.com/goravel/framework` from v1.15.6 to v1.15.7.
* Updated `github.com/dromara/carbon/v2` from v2.5.2 to v2.5.6.

upgrade: v1.15.7

---

app/models/user.go
database/migrations/20210101000001_create_users_table.go

This pull request introduces several updates, including a migration from MySQL to PostgreSQL, enhancements to configuration files, and updates to dependencies. The changes also include adjustments to README files, new database migrations, and minor code refinements. Below is a summary of the most important changes grouped by theme:

feat: optimize migration

---

go.mod
go.sum

This pull request includes a minor update to the `go.mod` file, upgrading the `github.com/goravel/framework` dependency from version `v1.15.8` to `v1.15.9`.

upgrade: v1.15.9

---

config/queue.go

This pull request removes support for the "machinery" driver in the queue configuration. The changes simplify the configuration by eliminating the "machinery" driver and its associated settings.
Queue configuration updates:
* [`config/queue.go`](diffhunk://#diff-85bf9343cdc5a94fcc6f7f5436c4898428d6df30e98848af4643fa64b9901d21L16-R16): Removed "machinery" from the list of supported drivers and deleted its configuration block, including settings for driver type, connection, queue name, and concurrency. [[1]](diffhunk://#diff-85bf9343cdc5a94fcc6f7f5436c4898428d6df30e98848af4643fa64b9901d21L16-R16) [[2]](diffhunk://#diff-85bf9343cdc5a94fcc6f7f5436c4898428d6df30e98848af4643fa64b9901d21L27-L32)

chore: optimzie queue

---

go.mod
go.sum

upgrade: v1.15.10
